development:
  adapter: postgresql
  database: legislativelookup
  username: legislativelookup
  password: pBe29jXLn3awCgnydlckNyTalwAw2lj4B5ZKK6mNxqeoeKF7XjEUxVnqj7VBgbR
  host: localhost

test:
  adapter: postgresql
  database: congress_test
  username: legislativelookup
  password: pBe29jXLn3awCgnydlckNyTalwAw2lj4B5ZKK6mNxqeoeKF7XjEUxVnqj7VBgbR
  host: localhost

production:
  adapter: postgresql
  database: legislativelookup
  username: legislativelookup
  password: pBe29jXLn3awCgnydlckNyTalwAw2lj4B5ZKK6mNxqeoeKF7XjEUxVnqj7VBgbR
  host: localhost
